spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: null
            client-secret: null
            redirect-uri: null
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_image
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: ${JWT_SECRET}
  access.expiration: 21600
  refresh.expiration: 86400
