server:
  port: 8080

spring:
  application:
    name: meow-chatting

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3400/meow?useSSL=false&allowPublicKeyRetrieval=true
    username: meow
    password: 1234qwer

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  flyway:
    enabled: false
    outOfOrder: true

redis:
  host: localhost
  port: 6400

jwt:
  secret-key: ${JWT_SECRET}
  access.expiration: 21600
  refresh.expiration: 86400
